// Benchmark harness for svg-power-opt.
//
// Measures four workloads against the current library:
//   A) Single-file repeated optimize()           - pure CPU, no I/O
//   B) Full corpus via optimizeSVGFromFile()     - sequential, per-file overhead
//   C) Full corpus via real CLI (async path)     - end-to-end baseline
//   D) Full corpus via real CLI with --workers   - end-to-end worker pool
//
// To compare against a previous revision, run this script, git checkout the
// other revision, run it again, and diff the numbers. A corpus of synthetic
// SVGs is generated by bench/make-corpus.js (245 files, ~5 MB).

import fs from "fs-extra";
import path from "path";
import os from "os";
import { spawn } from "child_process";
import { performance } from "perf_hooks";
import { fileURLToPath } from "url";

import { optimizeSVG, optimizeSVGFromFile } from "../lib/index.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const CORPUS = path.join(__dirname, "corpus");

const REPS = Number(process.env.REPS || 3);
const A_ITERS = Number(process.env.A_ITERS || 30);

if (!(await fs.pathExists(CORPUS))) {
  console.error(`No corpus found at ${CORPUS}. Run: node bench/make-corpus.js`);
  process.exit(1);
}

const files = (await fs.readdir(CORPUS))
  .filter((f) => f.endsWith(".svg") || f.endsWith(".svgz"))
  .map((f) => path.join(CORPUS, f));

const totalInputBytes = (
  await Promise.all(files.map((f) => fs.stat(f)))
).reduce((s, st) => s + st.size, 0);

const median = (arr) => {
  const s = arr.slice().sort((a, b) => a - b);
  return s[Math.floor(s.length / 2)];
};
const fmt = (n, d = 2) => Number(n.toFixed(d));

function summarize(mss, bytesIn, bytesOut, count) {
  const ms = median(mss);
  const sec = ms / 1000;
  return {
    medianMs: fmt(ms),
    filesPerSec: fmt(count / sec),
    mbInPerSec: fmt((bytesIn / 1024 / 1024) / sec, 3),
    reductionPct: bytesIn > 0 ? fmt(((bytesIn - bytesOut) / bytesIn) * 100) : 0,
  };
}

async function workloadA(aggressive) {
  const mid = files.find((f) => path.basename(f).startsWith("medium-")) || files[0];
  const content = await fs.readFile(mid, "utf-8");
  for (let i = 0; i < 3; i++) optimizeSVG(content, { aggressive }); // warmup
  const mss = [];
  let outBytes = 0;
  for (let rep = 0; rep < REPS; rep++) {
    outBytes = 0;
    const t0 = performance.now();
    for (let i = 0; i < A_ITERS; i++) {
      const r = optimizeSVG(content, { aggressive });
      outBytes += Buffer.byteLength(r.data, "utf-8");
    }
    mss.push(performance.now() - t0);
  }
  return summarize(mss, Buffer.byteLength(content, "utf-8") * A_ITERS, outBytes, A_ITERS);
}

async function workloadB(aggressive) {
  const mss = [];
  let outBytes = 0;
  for (let rep = 0; rep < REPS; rep++) {
    outBytes = 0;
    const t0 = performance.now();
    for (const f of files) {
      const out = await optimizeSVGFromFile(f, { aggressive });
      outBytes += Buffer.byteLength(out, "utf-8");
    }
    mss.push(performance.now() - t0);
  }
  return summarize(mss, totalInputBytes, outBytes, files.length);
}

async function cliRun(args, outDir) {
  await fs.emptyDir(outDir);
  const t0 = performance.now();
  await new Promise((resolve, reject) => {
    const child = spawn(
      process.execPath,
      [path.join(ROOT, "bin", "cli.js"), ...args, "--out", outDir],
      { stdio: "ignore" }
    );
    child.once("exit", (code) =>
      code === 0 ? resolve() : reject(new Error(`cli exit ${code}`))
    );
  });
  const ms = performance.now() - t0;
  let outBytes = 0;
  let count = 0;
  for (const f of await fs.readdir(outDir)) {
    if (!f.endsWith(".svg")) continue;
    outBytes += (await fs.stat(path.join(outDir, f))).size;
    count++;
  }
  return { ms, outBytes, count };
}

async function workloadCliAsync(aggressive) {
  const glob = path.join(CORPUS, "*.svg").replace(/\\/g, "/");
  const mss = [];
  let outBytes = 0;
  let count = 0;
  for (let rep = 0; rep < REPS; rep++) {
    const args = [glob];
    if (aggressive) args.push("--aggressive");
    const r = await cliRun(args, path.join(__dirname, "output", "cli-async"));
    mss.push(r.ms);
    outBytes = r.outBytes;
    count = r.count;
  }
  return summarize(mss, totalInputBytes, outBytes, count || 1);
}

async function workloadCliWorkers(aggressive) {
  const glob = path.join(CORPUS, "*.svg").replace(/\\/g, "/");
  const mss = [];
  let outBytes = 0;
  let count = 0;
  for (let rep = 0; rep < REPS; rep++) {
    const args = [glob, "--workers"];
    if (aggressive) args.push("--aggressive");
    const r = await cliRun(args, path.join(__dirname, "output", "cli-workers"));
    mss.push(r.ms);
    outBytes = r.outBytes;
    count = r.count;
  }
  return summarize(mss, totalInputBytes, outBytes, count || 1);
}

console.log(`\n== svg-power-opt benchmark ==`);
console.log(`Node ${process.version} on ${os.platform()} ${os.arch()}, CPUs=${os.cpus().length}`);
console.log(`Corpus: ${files.length} files, ${(totalInputBytes / 1024).toFixed(1)} KB, REPS=${REPS}\n`);

const rows = [];
for (const aggressive of [false, true]) {
  const mode = aggressive ? "aggressive" : "safe";
  rows.push({ workload: `A single-file x${A_ITERS}`, mode, ...(await workloadA(aggressive)) });
  rows.push({ workload: "B corpus sequential",       mode, ...(await workloadB(aggressive)) });
  rows.push({ workload: "C CLI async",               mode, ...(await workloadCliAsync(aggressive)) });
  rows.push({ workload: "D CLI --workers",           mode, ...(await workloadCliWorkers(aggressive)) });
}
console.table(rows);

await fs.writeJson(
  path.join(__dirname, "results.json"),
  { node: process.version, reps: REPS, rows },
  { spaces: 2 }
);
console.log(`\nSaved ${path.join(__dirname, "results.json")}`);
